language: bash

sudo: required

services:
- docker

branches:
  only:
  - dev

script:
- echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build --tag olegschwann/authorization_server ./authorization_server/
- docker push olegschwann/authorization_server
- docker build --tag olegschwann/game_server ./game_server/
- docker push olegschwann/game_server
- ssh-keyscan -H 95.163.212.32 >> ~/.ssh/known_hosts
- chmod 400 2018_2_42_id_rsa.pem
- cat restart_containers.sh | ssh ubuntu@95.163.212.32 -i './2018_2_42_id_rsa.pem'

before_install:
- openssl aes-256-cbc -K $encrypted_7decf5f4bb11_key -iv $encrypted_7decf5f4bb11_iv
  -in 2018_2_42_id_rsa.pem.enc -out ./2018_2_42_id_rsa.pem -d
