language: go

go:
- "1.10.x"

sudo: required

services:
- docker

branches:
  only:
  - dev

script:
- wget --no-verbose --output-document ~/'gometalinter-2.0.12-linux-amd64.tar.gz' 'https://github.com/alecthomas/gometalinter/releases/download/v2.0.12/gometalinter-2.0.12-linux-amd64.tar.gz';
- tar --verbose --extract --file ~/'gometalinter-2.0.12-linux-amd64.tar.gz' --directory ~/;
- export PATH="${PATH}:${HOME}/gometalinter-2.0.12-linux-amd64";
- ~/'gometalinter-2.0.12-linux-amd64/gometalinter' --config '.gometalinter.json' --cyclo-over 24 --exclude 'easyjson.go';
- docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}";
- docker build --tag olegschwann/authorization_server ./authorization_server/
- docker push olegschwann/authorization_server
- docker build --tag olegschwann/game_server ./game_server/
- docker push olegschwann/game_server
- ssh-keyscan -H 95.163.212.32 >> ~/.ssh/known_hosts
- chmod 400 2018_2_42_id_rsa.pem
- cat restart_containers.sh | ssh ubuntu@95.163.212.32 -i './2018_2_42_id_rsa.pem'

before_install:
- openssl aes-256-cbc -K $encrypted_7decf5f4bb11_key -iv $encrypted_7decf5f4bb11_iv
  -in 2018_2_42_id_rsa.pem.enc -out ./2018_2_42_id_rsa.pem -d
